name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Build frontend
        run: npm run build
  Cypress-test:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
      
          - name: Install Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '20'  # Use Node.js 20
              cache: 'npm'
      
          - name: Clean node_modules
            run: rm -rf node_modules  # Clear the node_modules directory
      
          - name: Install dependencies
            run: npm ci  # Use `npm ci` for a clean install
      
          - name: Start development server
            run: npm start &  # Start the development server in the background
      
          - name: Run Cypress tests
            uses: cypress-io/github-action@v6
            with:
              start: npm start
              wait-on: 'http://localhost:3000'  # Wait for the server to start
      

