name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Build frontend
        run: npm run build
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: |
          npm install
          npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Run Cypress tests
        run: npx cypress run  # Runs Cypress in headless mode
      

