name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the Node.js version required by your React project

      - name: Install dependencies
        run: npm install  # Or `yarn install` if using Yarn

      - name: Build frontend
        run: npm run build  # O
 Cypress-test:
     runs-on: ubuntu-24.04
     needs: [ build ]
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
 docker:
    runs-on: ubuntu-latest
    needs: Cypress-test
    steps:
   
    - name: Checkout code
      uses: actions/checkout@v3

   
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t sallyphaan/frontendindividualss6:latest .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push sallyphaan/frontendindividualss6:latest
